BuildVersion = "0.0.0.1" -- updated by the compiler
PluginInfo = {
  Name = "Samsung~TV Control v" .. BuildVersion,
  Version = BuildVersion,
  Id = "a7fc8f72-9e1a-4eb9-873a-b83b46ccc9ef", -- generated by the compiler on first build; NEVER change it afterwards
  Author = "Bayside Church",
  Description = "Control of Samsung televisions — consumer Tizen sets via IP Control (JSON-RPC) and the Tizen websocket remote, plus commercial panels via MDC.",
  Manufacturer = "Samsung",
}
